# fly.toml app configuration file generated for lakshmy-backend on 2025-05-29T08:13:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml app configuration file for lakshmy-backend

app = "lakshmy-backend"
primary_region = "bom"

[build]

[[services]]
internal_port = 8000
protocol = "tcp"

auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1

